//48 [181,199]
var curs = [
'WHEAT-SRW - CHICAGO BOARD OF TRADE',
'BLACK SEA WHEAT FINANCIAL - CHICAGO BOARD OF TRADE',
'WHEAT-HRW - CHICAGO BOARD OF TRADE',
'WHEAT-HRSpring - MINNEAPOLIS GRAIN EXCHANGE',
'CORN - CHICAGO BOARD OF TRADE',
'OATS - CHICAGO BOARD OF TRADE',
'SOYBEANS - CHICAGO BOARD OF TRADE',
'MINI SOYBEANS - CHICAGO BOARD OF TRADE',
'NJ SRECS VINTAGE 2018 - ICE FUTURES ENERGY DIV',
'CALIF CARBON ALL VINTAGE 2017 - ICE FUTURES ENERGY DIV',
'CALIF CARBON ALL VINTAGE 2018 - ICE FUTURES ENERGY DIV',
'NJ SRECS VINTAGE 2019 - ICE FUTURES ENERGY DIV',
'NJ SRECS VINTAGE 2020 - ICE FUTURES ENERGY DIV',
'PJM TRI-RECs CLASS 1 Vin 2018 - ICE FUTURES ENERGY DIV',
'PJM TRI-RECs CLASS 1 Vin 2019 - ICE FUTURES ENERGY DIV',
'PJM TRI-RECs CLASS 1 Vin 2020 - ICE FUTURES ENERGY DIV',
'RGGI VINTAGE 2017 - ICE FUTURES ENERGY DIV',
'CALIF CARBON ALL VINTAGE 2019 - ICE FUTURES ENERGY DIV',
'PJM TRI-RECs CLASS 1 Vin 2021 - ICE FUTURES ENERGY DIV',
'NJ SRECS VINTAGE 2021 - ICE FUTURES ENERGY DIV',
'RGGI VINTAGE 2018 - ICE FUTURES ENERGY DIV',
'SOYBEAN OIL - CHICAGO BOARD OF TRADE',
'USGC HSFO (PLATTS) - ICE FUTURES ENERGY DIV',
'3% FUEL OIL USGC VS. 3.5%FUEL OIL FOB ROTTERDAM BARGES - ICE FUTURES ENERGY DIV',
'GULF # 6 FUEL 3.0% SULFUR SWAP - NEW YORK MERCANTILE EXCHANGE',
'EUR 3.5% FUEL OIL RTD CAL SWAP - NEW YORK MERCANTILE EXCHANGE',
'SING 380 FUEL OIL SWAP - NEW YORK MERCANTILE EXCHANGE',
'MINI EUR 3.5%FOIL RTD CAL SWAP - NEW YORK MERCANTILE EXCHANGE',
'GULF NO6 FO 3% v EUR 3.5% RDAM - NEW YORK MERCANTILE EXCHANGE',
'MINI SING 380 FUEL OIL SWAP - NEW YORK MERCANTILE EXCHANGE',
'FUEL OIL-380cst SING/3.5% RDAM - NEW YORK MERCANTILE EXCHANGE',
'#2 HEATING OIL- NY HARBOR-ULSD - NEW YORK MERCANTILE EXCHANGE',
'UP DOWN GC ULSD VS HO SPR - NEW YORK MERCANTILE EXCHANGE',
'NATURAL GAS HENRY LD1 FIXED - ICE FUTURES ENERGY DIV',
'NATURAL GAS PENULTIMATE ICE - ICE FUTURES ENERGY DIV',
'SOCAL BORDER FIN BASIS - ICE FUTURES ENERGY DIV',
'PG&E CITYGATE FIN BASIS - ICE FUTURES ENERGY DIV',
'NWP ROCKIES FIN BASIS - ICE FUTURES ENERGY DIV',
'AECO FIN BASIS - ICE FUTURES ENERGY DIV',
'CHICAGO FIN BASIS - ICE FUTURES ENERGY DIV',
'HSC FIN BASIS - ICE FUTURES ENERGY DIV',
'WAHA FIN BASIS - ICE FUTURES ENERGY DIV',
'ALGONQUIN CITY-GATES FINANCIAL BASIS - ICE FUTURES ENERGY DIV',
'CHICAGO CITYGATE (INDEX) - ICE FUTURES ENERGY DIV',
'COLORADO INTERSTATE - MAINLINE (BASIS) - ICE FUTURES ENERGY DIV',
'COLUMBIA GAS CO. - TCO POOL (APPALACHIA) (BASIS) - ICE FUTURES ENERGY DIV',
'COLUMBIA GULF TRANSMISSION CO. -  MAINLINE POOL - ICE FUTURES ENERGY DIV',
'DOMINION - SOUTH POINT - ICE FUTURES ENERGY DIV',
'DOMINION - SOUTH POINT (BASIS) - ICE FUTURES ENERGY DIV',
'EL PASO - PERMIAN BASIN (BASIS) - ICE FUTURES ENERGY DIV',
'EL PASO - PERMIAN BASIN (INDEX) - ICE FUTURES ENERGY DIV',
'EL PASO-SAN JUAN BASIN-BLANCO POOL PRIMARY ONLY-BASIS - ICE FUTURES ENERGY DIV',
'HENRY HUB - TAILGATE LOUISIANA (BASIS) - ICE FUTURES ENERGY DIV',
'HENRY HUB - TAILGATE LOUISIANA (INDEX) - ICE FUTURES ENERGY DIV',
'HOUSTON SHIP CHANNEL (INDEX) - ICE FUTURES ENERGY DIV',
'MICHIGAN CONSOLIDATED CITYGATE (GENERIC) (BASIS) - ICE FUTURES ENERGY DIV',
'NATURAL GAS INDEX: ALGONQUIN CITY GATES - ICE FUTURES ENERGY DIV',
'NATURAL GAS PIPELINE-MID-CONTINENT POOL PIN (BASIS) - ICE FUTURES ENERGY DIV',
'NATURAL GAS PIPELINE-TEXOK (BASIS) - ICE FUTURES ENERGY DIV',
'NORTHERN NATURAL GAS - VENTURA (BASIS) - ICE FUTURES ENERGY DIV',
'NORTHWEST PIPELINE - CANADIAN BORDER (BASIS) - ICE FUTURES ENERGY DIV',
'NORTHWEST PIPELINE CORP. - ROCKY MOUNTAINS - ICE FUTURES ENERGY DIV',
'PACIFIC GAS TRANSMISSION - MALIN (BASIS) - ICE FUTURES ENERGY DIV',
'PANHANDLE EASTERN- POOL GAS (BASIS) - ICE FUTURES ENERGY DIV',
'TEXAS EASTERN- M3 ZONE (DELIVERED) - ICE FUTURES ENERGY DIV',
'TEXAS EASTERN- M3 ZONE (DELIVERED) (BASIS) - ICE FUTURES ENERGY DIV',
'TRANSCO ZONE 6 BASIS - ICE FUTURES ENERGY DIV',
'TRANSCONTINENTAL GAS- STATION 85 (ZONE 4) - ICE FUTURES ENERGY DIV',
'TRANSCONTINENTAL GAS - ZONE 6 (NY) (BASIS) - ICE FUTURES ENERGY DIV',
"WAHA HUB - WEST TEXAS DELIVERED/BUYER'S INDEX - ICE FUTURES ENERGY DIV",
'TETCO M2 Basis (Receipts) - ICE FUTURES ENERGY DIV',
'TRANSCO LEIDY BASIS - ICE FUTURES ENERGY DIV',
'REX ZONE 3 BASIS - ICE FUTURES ENERGY DIV',
'NATURAL GAS - NEW YORK MERCANTILE EXCHANGE',
'HENRY HUB LAST DAY FIN - NEW YORK MERCANTILE EXCHANGE',
'HENRY HUB PENULTIMATE FIN - NEW YORK MERCANTILE EXCHANGE',
'HENRY HUB NAT GAS FINL-10000 - NASDAQ FUTURES',
'HHUB NAT GAS PENULT FINL-10000 - NASDAQ FUTURES',
'HHUB NAT GAS PENULT FINL-2500 - NASDAQ FUTURES',
'COAL (API 2) CIF ARA SWAP FUT - NEW YORK MERCANTILE EXCHANGE',
'COAL (API 4) FOB  RICH BAY FUT - NEW YORK MERCANTILE EXCHANGE',
'CBT ETHANOL - CHICAGO BOARD OF TRADE',
'ETHANOL T2 FOB INCL DUTY SWAP - NEW YORK MERCANTILE EXCHANGE',
'CHICAGO ETHANOL SWAP - NEW YORK MERCANTILE EXCHANGE',
'SOYBEAN MEAL - CHICAGO BOARD OF TRADE',
'EUROPEAN NAPHTHA CAL SWAP - NEW YORK MERCANTILE EXCHANGE',
'JAPAN C&F NAPHTHA SWAP - NEW YORK MERCANTILE EXCHANGE',
'Mini Eur Naphtha CIF NWE Swap - NEW YORK MERCANTILE EXCHANGE',
'COTTON NO. 2 - ICE FUTURES U.S.',
'HENRY HUB SWAP - NEW YORK MERCANTILE EXCHANGE',
'HENRY HUB PENULTIMATE GAS SWAP - NEW YORK MERCANTILE EXCHANGE',
'MALAYSIAN PALM OIL CALENDAR SW - CHICAGO MERCANTILE EXCHANGE',
'ROUGH RICE - CHICAGO BOARD OF TRADE',
'FRZN CONCENTRATED ORANGE JUICE - ICE FUTURES U.S.',
'BUTTER (CASH SETTLED) - CHICAGO MERCANTILE EXCHANGE',
'MILK, Class III - CHICAGO MERCANTILE EXCHANGE',
'NON FAT DRY MILK - CHICAGO MERCANTILE EXCHANGE',
'DRY WHEY - CHICAGO MERCANTILE EXCHANGE',
'LEAN HOGS - CHICAGO MERCANTILE EXCHANGE',
'LIVE CATTLE - CHICAGO MERCANTILE EXCHANGE',
'RANDOM LENGTH LUMBER - CHICAGO MERCANTILE EXCHANGE',
'FEEDER CATTLE - CHICAGO MERCANTILE EXCHANGE',
'CHEESE (CASH-SETTLED) - CHICAGO MERCANTILE EXCHANGE',
'PJM WH REAL TIME PEAK - ICE FUTURES ENERGY DIV',
'MID-C DAY-AHEAD PEAK - ICE FUTURES ENERGY DIV',
'MID-C DAY-AHEAD OFF-PEAK - ICE FUTURES ENERGY DIV',
'PJM WESTERN HUB RT OFF - ICE FUTURES ENERGY DIV',
'SP15 FIN DA PEAK FIXED - ICE FUTURES ENERGY DIV',
'CAISO SP15 FIN DA OFF-PEAK - ICE FUTURES ENERGY DIV',
'PJM AEP DAYTON RT OFF-PK - ICE FUTURES ENERGY DIV',
'PJM AEP DAYTON RT PEAK FIXED - ICE FUTURES ENERGY DIV',
'PJM AEP DAYTON HUB DA OFF-PK  - ICE FUTURES ENERGY DIV',
'PJM AEP DAYTON DA PEAK - ICE FUTURES ENERGY DIV',
'MISO INDIANA  OFF-PEAK - ICE FUTURES ENERGY DIV',
'MISO IN. REAL-TIME OFF-PEAK - ICE FUTURES ENERGY DIV',
'ERCOT HOUSTON 345KV RT PK FIX - ICE FUTURES ENERGY DIV',
'ERCOT NORTH 345KV RT PK FIX - ICE FUTURES ENERGY DIV',
'ERCOT - NORTH MONTHLY OFF-PEAK - ICE FUTURES ENERGY DIV',
'MISO IN. DAY-AHEAD PEAK - ICE FUTURES ENERGY DIV',
'MISO INDIANA HUB RT PEAK - ICE FUTURES ENERGY DIV',
'PJM N. IL HUB DA OFF-PK  - ICE FUTURES ENERGY DIV',
'PJM N. IL HUB DA PEAK - ICE FUTURES ENERGY DIV',
'ISO NE MASS HUB DA OFF-PK - ICE FUTURES ENERGY DIV',
'ISO NE MASS HUB DA PEAK - ICE FUTURES ENERGY DIV',
'CAISO NP-15 PEAK - ICE FUTURES ENERGY DIV',
'PJM NI HUB RT OFF-PK - ICE FUTURES ENERGY DIV',
'PJM N. IL HUB RT PEAK - ICE FUTURES ENERGY DIV',
'NYISO ZONE J DA PEAK - ICE FUTURES ENERGY DIV',
'NYISO ZONE J DA OFF-PK - ICE FUTURES ENERGY DIV',
'NYISO ZONE A DA PEAK - ICE FUTURES ENERGY DIV',
'NYISO ZONE A DA OFF-PK - ICE FUTURES ENERGY DIV',
'NYISO ZONE G DA PEAK - ICE FUTURES ENERGY DIV',
'NYISO ZONE G DA OFF-PK - ICE FUTURES ENERGY DIV',
'PALO VERDE DA PEAK - ICE FUTURES ENERGY DIV',
'PJM BGE ZONE DAY AHEAD OFF PEAK MONTHLY - ICE FUTURES ENERGY DIV',
'PJM BGE ZONE DAY AHEAD, PEAK MONTHLY - ICE FUTURES ENERGY DIV',
'PJM COMED ZONE DAY AHEAD LMP PEAK MONTHLY - ICE FUTURES ENERGY DIV',
'PJM PECO ZONE DA PEAK - ICE FUTURES ENERGY DIV',
'PJM PECO ZONE OFF-PEAK MONTHLY - ICE FUTURES ENERGY DIV',
'PJM PEPCO DA PEAK - ICE FUTURES ENERGY DIV',
'PJM PEPCO DAY-AHEAD OFF-PEAK - ICE FUTURES ENERGY DIV',
'PJM PPL ZONE DAY AHEAD, OFF-PEAK MONTHLY - ICE FUTURES ENERGY DIV',
'PJM PPL ZONE DA PEAK - ICE FUTURES ENERGY DIV',
'PJM WESTERN HUB DA OFF-PK - ICE FUTURES ENERGY DIV',
'PJM WESTERN HUB DA PEAK - ICE FUTURES ENERGY DIV',
'PJM WESTERN HUB RT PEAK MINI - ICE FUTURES ENERGY DIV',
'PJM PSEG DAY-AHEAD PEAK - ICE FUTURES ENERGY DIV',
'PJM PSEG ZONE DAY-AHEAD OFF-PEAK - ICE FUTURES ENERGY DIV',
'MISO.INDIANA.HUB_month_on_dap - NODAL EXCHANGE',
'MISO.INDIANA.HUB_month_off_dap - NODAL EXCHANGE',
'PJM.AEP-DAYTON HUB_month_on_dap - NODAL EXCHANGE',
'PJM.AEP-DAYTON HUB_month_off_dap - NODAL EXCHANGE',
'PJM.BGE_month_on_dap - NODAL EXCHANGE',
'PJM.BGE_month_off_dap - NODAL EXCHANGE',
'PJM.N ILLINOIS HUB_month_on_dap - NODAL EXCHANGE',
'PJM.PECO_month_on_dap - NODAL EXCHANGE',
'PJM.PECO_month_off_dap - NODAL EXCHANGE',
'PJM.PPL_month_on_dap - NODAL EXCHANGE',
'PJM.PPL_month_off_dap - NODAL EXCHANGE',
'PJM.PSEG_month_on_dap - NODAL EXCHANGE',
'PJM.PSEG_month_off_dap - NODAL EXCHANGE',
'PJM.WESTERN HUB_month_on_dap - NODAL EXCHANGE',
'PJM.WESTERN HUB_month_off_dap - NODAL EXCHANGE',
'PJM.AEP-DAYTON HUB_month_on_rtp - NODAL EXCHANGE',
'PJM.AEP-DAYTON HUB_month_off_rtp - NODAL EXCHANGE',
'PJM.WESTERN HUB_month_on_rtp - NODAL EXCHANGE',
'PJM.WESTERN HUB_month_off_rtp - NODAL EXCHANGE',
'ARGUS FAR EAST SWAP PROPANE - ICE FUTURES ENERGY DIV',
'ETHANE, MT. BELV-ENTERPRISE - ICE FUTURES ENERGY DIV',
'NAT GASLNE OPIS MT B NONTET FP - ICE FUTURES ENERGY DIV',
'BUTANE OPIS MT BELV NONTET FP  - ICE FUTURES ENERGY DIV',
'PROPANE OPIS MT BELV NONTET FP - ICE FUTURES ENERGY DIV',
'PROPANE OPIS MT BELVIEU TET FP - ICE FUTURES ENERGY DIV',
'ARGUS PROPANE FAR EAST INDEX - NEW YORK MERCANTILE EXCHANGE',
'PROPANE NON-LDH MT BEL SWAP - NEW YORK MERCANTILE EXCHANGE',
'MT BELVIEU LDH PROPANE (OPIS) - NEW YORK MERCANTILE EXCHANGE',
'MT BELVIEU ETHANE OPIS - NEW YORK MERCANTILE EXCHANGE',
'MT BELV NORM BUTANE OPIS - NEW YORK MERCANTILE EXCHANGE',
'MT BELV NAT GASOLINE OPIS SWAP - NEW YORK MERCANTILE EXCHANGE',
'CONWAY PROPANE (OPIS) - NEW YORK MERCANTILE EXCHANGE',
'CRUDE OIL, LIGHT SWEET-WTI - ICE FUTURES EUROPE',
'CRUDE DIFF-TMX WCS 1A INDEX - ICE FUTURES ENERGY DIV',
'ARGUS MARS vs WTI TRADE MONTH - ICE FUTURES ENERGY DIV',
'ARGUS WTI Mid/WTI TRADE MONTH - ICE FUTURES ENERGY DIV',
'CRUDE OIL, LIGHT SWEET - NEW YORK MERCANTILE EXCHANGE',
'WTI CRUDE OIL CALENDAR SWAP - NEW YORK MERCANTILE EXCHANGE',
'WTI-BRENT CALENDAR SWAP - NEW YORK MERCANTILE EXCHANGE',
'BRENT CRUDE OIL LAST DAY - NEW YORK MERCANTILE EXCHANGE',
'WTI  HOUSTON ARGUS/WTI TR MO - NEW YORK MERCANTILE EXCHANGE',
'WTI MIDLAND ARGUS VS WTI TRADE - NEW YORK MERCANTILE EXCHANGE',
'WCS OIL NET ENERGY MONTHLY IND - NEW YORK MERCANTILE EXCHANGE',
'COCOA - ICE FUTURES U.S.',
'PALLADIUM - NEW YORK MERCANTILE EXCHANGE',
'PLATINUM - NEW YORK MERCANTILE EXCHANGE',
'SUGAR NO. 11 - ICE FUTURES U.S.',
'COFFEE C - ICE FUTURES U.S.',
'SILVER - COMMODITY EXCHANGE INC.',
'COPPER-GRADE #1 - COMMODITY EXCHANGE INC.',
'GOLD - COMMODITY EXCHANGE INC.',
'GASOLINE CRK-RBOB/BRENT 1st - ICE FUTURES ENERGY DIV',
'GASOLINE BLENDSTOCK (RBOB)  - NEW YORK MERCANTILE EXCHANGE',
'RBOB CALENDAR SWAP - NEW YORK MERCANTILE EXCHANGE',
'GULF COAST UNL 87 GAS M2 PL RB - NEW YORK MERCANTILE EXCHANGE',
'RBOB GASOLINE/BRENT CRACK SPRD - NEW YORK MERCANTILE EXCHANGE',
'ALUMINUM MW US TR PLATTS SWAP - COMMODITY EXCHANGE INC.',
'HOT ROLLED COIL STEEL - NEW YORK MERCANTILE EXCHANGE',
'IRON ORE 62% FE-CFR CHINA TSI - NEW YORK MERCANTILE EXCHANGE',
'GULF JET NY HEAT OIL SPR SWAP - NEW YORK MERCANTILE EXCHANGE',
'SING JET KERO GASOIL SPR SWAP - NEW YORK MERCANTILE EXCHANGE',
'3.5% FUEL OIL RDAM CRACK SPR  - NEW YORK MERCANTILE EXCHANGE',
'NAPHTHA CRACK SPR SWAP - NEW YORK MERCANTILE EXCHANGE',
'MINI JAPAN C&F NAPHTHA SWAP FU - NEW YORK MERCANTILE EXCHANGE',
'EUROBOB OXY NWE CRK SPR  - NEW YORK MERCANTILE EXCHANGE',
];
//16 [1,2]
//var pats2 = [
//'Other_Rept_Positions_Long_All c1, Other_Rept_Positions_Short_All c2',
//'NonRept_Positions_Long_All c1,	NonRept_Positions_Short_All c2',
//];
var pats2 = [
'M_Money_Positions_Long_All c1, M_Money_Positions_Short_All c2',
'NonRept_Positions_Long_All c1,	NonRept_Positions_Short_All c2',
];

var Cot = require('./cot2').cot, sqlite3 = require('sqlite3');

function cot2_dao(){
	var db = new sqlite3.Database("C:/rou/db/abc.db");

	this.retrieve = function(id, params, callback){
		//var cots = [];
		var cots = {};
		var catgs = [];
		var data = {};
		var d1 = [];
		var d2 = [];
		var n = parseInt(id);
		var pat = n%100;
		var cur = parseInt(n/100);
		//console.log("cur=");
		//console.log(cur);
		//console.log("pat=");
		//console.log(pat);
		var sql = '';
		if (cur>0 && pat>0) {
			//sql = "select As_of_Date_In_Form_YYMMDD a, Market_and_Exchange_Names b, " +
			//pats[pat-1] + " c from cot where b = '" + curs[cur-1] + "' order by a";
			sql = "select As_of_Date_In_Form_YYMMDD a, Market_and_Exchange_Names b, " +
			pats2[pat-1] + " from disagg where b = '" + curs[cur-1] + "' order by a desc limit 50";
			//console.log("sql=");
			//console.log(sql);
		}
		//db.all("select As_of_Date_In_Form_YYMMDD a, Market_and_Exchange_Names b, \
		//	Dealer_Positions_Long_All c from cot where b = ? \
		//	and a = ?", [cur[3], id],
		db.all(sql, [], 
			function(err, rows, fields) {
				if (err) throw err;
			    for(var i=rows.length-1; i>=0; i--){
					//var cot = new Cot(rows[i].As_of_Date_In_Form_YYMMDD, rows[i].Market_and_Exchange_Names, rows[i].Dealer_Positions_Long_All);
					//var cot = new Cot(rows[i].a, rows[i].b, rows[i].c);
					//cots.push(cot);
					catgs.push(rows[i].a);
					//data.push(rows[i].c);
					d1.push(rows[i].c1);
					d2.push(-rows[i].c2);
				}
				data['1'] = d1;
				data['2'] = d2;
				cots['catg'] = catgs;
				cots['data'] = data;
				callback(cots);
				db.close();
			}
		);
	};
	
}

exports.dao = cot2_dao;
